version: '3.9'

networks:
  effecti:

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5342:5432"
    volumes:
      - "./.docker/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: effecti
      POSTGRES_PASSWORD: 1233219
      POSTGRES_HOST_AUTH_METHOD: trust
  
  cache:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6397:6379"
    depends_on:
      - db
    networks:
      - effecti

  api:
    build: ./.docker/php
    container_name: php
    volumes:
      - ./api:/var/www
    depends_on:
      - db
      - cache
    networks:
      - effecti  

  server:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./api:/var/www
    depends_on:
      - db
      - cache
      - api
    networks:
      - effecti  

  app:
    build:
      context: .
      dockerfile: Appfile
    container_name: node
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
      - api
      - server
    environment:
      NODE_ENV: development
    networks:
      - effecti

volumes:
  postgres:
    driver: local
